apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: howdy
  name: howdy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: howdy
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: howdy
    spec:
      containers:
        - args:
            - ./multijohn
            - --mode=howdy
            - --logLevel={{ .Values.multijohn.logLevel }}
          env:
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "etcd:{{ .Values.etcd.port }}"
          image: "{{ .Values.multijohn.imageName }}"
          imagePullPolicy: Always
          name: howdy
          ports:
            - containerPort: {{ int .Values.multijohn.howdy.port }}
          resources: {}
      restartPolicy: Always
status: {}
