apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: howdy
  name: howdy
spec:
  ports:
    - name: "{{ .Values.multijohn.howdy.port }}"
      port: {{ .Values.multijohn.howdy.port }}
      targetPort: {{ .Values.multijohn.howdy.port }}
  selector:
    io.kompose.service: howdy
  type: NodePort
status:
  loadBalancer: {}
