multijohn:
    # Common configuration across the entire application.
    totalNodes: 5
    imageName: praktiskt/multi-john:latest
    logLevel: debug

    # Howdy is where you can find your results.
    howdy:
        port: 8080
        serviceType: NodePort

    # A node is one worker, running john on one shard out of all totalNodes.
    node:
        requests:
            memory: "64Mi"
            cpu: "250m"
        limits:
            memory: "128Mi"
            cpu: "500m"
        # This is where you specify what flags to pass to john. This includes what kind of hashes are part of johnFile.
        johnFlags: --format=raw-sha256
        # This is where to find the john binary in the container.
        johnPath: /jtr/run/john
        # The contents of the file to process.
        johnFile: 
            path: /input
            file: dummy
            # This is the base64 representation of the file containing your hashes. Use something like `cat file | base64` and paste here.
            input: Y2E5NzgxMTJjYTFiYmRjYWZhYzIzMWIzOWEyM2RjNGRhNzg2ZWZmODE0N2M0ZTcyYjk4MDc3ODVhZmVlNDhiYgozZTIzZTgxNjAwMzk1OTRhMzM4OTRmNjU2NGUxYjEzNDhiYmQ3YTAwODhkNDJjNGFjYjczZWVhZWQ1OWMwMDlkCjJlN2QyYzAzYTk1MDdhZTI2NWVjZjViNTM1Njg4NWE1MzM5M2EyMDI5ZDI0MTM5NDk5NzI2NWExYTI1YWVmYzYKMThhYzNlNzM0M2YwMTY4OTBjNTEwZTkzZjkzNTI2MTE2OWQ5ZTNmNTY1NDM2NDI5ODMwZmFmMDkzNGY0ZjhlNApmYjhlMjBmYzJlNGMzZjI0OGM2MGMzOWJkNjUyZjNjMTM0NzI5OGJiOTc3YjhiNGQ1OTAzYjg1MDU1NjIwNjAzCmY0NWRlNTFjZGVmMzA5OTE1NTFlNDFlODgyZGQ3YjU0MDQ3OTk2NDhhMGEwMDc1M2Y0NGZjOTY2ZTYxNTNmYzEKYmE3ODE2YmY4ZjAxY2ZlYTQxNDE0MGRlNWRhZTIyMjNiMDAzNjFhMzk2MTc3YTljYjQxMGZmNjFmMjAwMTVhZAphNTJkMTU5ZjI2MmIyYzZkZGI3MjRhNjE4NDBiZWZjMzZlYjMwYzg4ODc3YTQwMzBiNjVjYmU4NjI5ODQ0OWM5Cjg4ZDQyNjZmZDRlNjMzOGQxM2I4NDVmY2YyODk1NzlkMjA5Yzg5NzgyM2I5MjE3ZGEzZTE2MTkzNmYwMzE1ODkKNWRjYmYxYzIxODY2NGU2ODRlNzZhOWU2MmZhN2U5MDU0ZjBiNjUxZTdiNGYyYzRlN2ViOGQyMWIyYzQ5Y2QyMgpiYzg5YjgzMDc1ZDZhYTZkOTExMTJhMTYxOGVkOWQzNmQ3Y2YzN2YzMzVmMjNhODg5YmE2N2Q4ZTVmNWQ0ODM5CjIxZTU2YmZiYWJhNTdjYjdlMDJmZmM4YmNkYTMwMTVkYWM4MmQzZjkxMGQ1MTJmNDY2NmJjMjNkOWRlY2M2Mzk= 

etcd:
    replicas: 1
    imageName: bitnami/etcd:latest
    port: 2379
    requests:
        memory: "128Mi"
        cpu: "1000m"
    limits:
        memory: "256Mi"
        cpu: "2000m"